#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Generated by O3DE

ly_add_target(
    NAME ProjectManager.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            3rdParty::Qt::Core
            3rdParty::Qt::Concurrent
            3rdParty::Qt::Widgets
            3rdParty::Python
            3rdParty::pybind11
            AZ::AzCore
            AZ::AzFramework
            AZ::AzToolsFramework
    RUNTIME_DEPENDENCIES
        3rdParty::Qt::Core
        3rdParty::Qt::Concurrent
        3rdParty::Qt::Widgets
        3rdParty::Python
        3rdParty::pybind11
        AZ::AzCore
        AZ::AzFramework
        AZ::AzToolsFramework
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/ProjectManager.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME ProjectManager IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        3rdParty::Qt::Core
        3rdParty::Qt::Concurrent
        3rdParty::Qt::Widgets
        3rdParty::Python
        3rdParty::pybind11
        AZ::AzCore
        AZ::AzFramework
        AZ::AzQtComponents
        AZ::AzToolsFramework
        AZ::ProjectManager.Static
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/ProjectManager_${config}.cmake" OPTIONAL)
endforeach()

