# Generated by O3DE install

set_property(TARGET ProjectManager
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./o3de>
)
set_property(TARGET ProjectManager
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./o3de
)
