# Generated by O3DE install

set_property(TARGET Launcher.Unified.Static
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/lib/Linux/profile/Default/libLauncher.Unified.Static.a>
)
set_property(TARGET Launcher.Unified.Static
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/lib/Linux/profile/Default/libLauncher.Unified.Static.a
)
