# Generated by O3DE install

set_property(TARGET O3DE.ServerLauncher
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./O3DE.ServerLauncher>
)
set_property(TARGET O3DE.ServerLauncher
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./O3DE.ServerLauncher
)
