# Generated by O3DE install

set_property(TARGET O3DE.HeadlessServerLauncher
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./O3DE.HeadlessServerLauncher>
)
set_property(TARGET O3DE.HeadlessServerLauncher
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Linux/profile/Default/./O3DE.HeadlessServerLauncher
)
