#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Generated by O3DE

ly_add_target(
    NAME Launcher.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/Launcher.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Headless.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework.Headless
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/Launcher.Headless.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Game.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        AZ::AzGameFramework
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/Launcher.Game.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Server.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/Launcher.Server.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Unified.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        AZ::AzGameFramework
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/Launcher.Unified.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME O3DE.GameLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Game.Static
        Atom.Clients
        AtomViewportDisplayInfo.Clients
        Atom_AtomBridge.Clients
        Atom_Bootstrap.Clients
        Camera.Clients
        CommonFeaturesAtom.Clients
        EMotionFX.Clients
        GradientSignal.Clients
        ImGui.Clients
        Legacy::CrySystem
        LmbrCentral.Clients
        Maestro.Clients
        SurfaceData.Clients
    TARGET_PROPERTIES
        LY_PROJECT_NAME O3DE
)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/O3DE.GameLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME O3DE.ServerLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::AzGameFramework
        AZ::Launcher.Server.Static
        Atom.Servers
        AtomViewportDisplayInfo.Servers
        Atom_AtomBridge.Servers
        Atom_Bootstrap.Servers
        Camera.Servers
        CommonFeaturesAtom.Servers
        EMotionFX.Servers
        GradientSignal.Servers
        ImGui.Servers
        Legacy::CrySystem
        LmbrCentral.Servers
        Maestro.Servers
        SurfaceData.Servers
    TARGET_PROPERTIES
        LY_PROJECT_NAME O3DE
)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/O3DE.ServerLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME O3DE.HeadlessServerLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Headless.Static
        AZ::AzGameFramework.Headless
        AZ::Launcher.Server.Static
        Atom.HeadlessServers
        AtomViewportDisplayInfo.Servers
        Atom_AtomBridge.HeadlessServers
        Atom_Bootstrap.Servers
        Atom_RHI_DX12.HeadlessServers
        Atom_RHI_Metal.HeadlessServers
        Atom_RHI_Vulkan.HeadlessServers
        Camera.Servers
        CommonFeaturesAtom.Servers
        EMotionFX.Servers
        GradientSignal.Servers
        ImGui.Servers
        Legacy::CrySystem
        LmbrCentral.Servers
        Maestro.Servers
        SurfaceData.Servers
    TARGET_PROPERTIES
        LY_PROJECT_NAME O3DE
)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/O3DE.HeadlessServerLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME O3DE.UnifiedLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Unified.Static
        Atom.Unified
        AtomViewportDisplayInfo.Unified
        Atom_AtomBridge.Unified
        Atom_Bootstrap.Unified
        Camera.Unified
        CommonFeaturesAtom.Unified
        EMotionFX.Unified
        GradientSignal.Unified
        ImGui.Unified
        Legacy::CrySystem
        LmbrCentral.Unified
        Maestro.Unified
        SurfaceData.Unified
    TARGET_PROPERTIES
        LY_PROJECT_NAME O3DE
)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Default/O3DE.UnifiedLauncher_${config}.cmake" OPTIONAL)
endforeach()

ly_set_gem_variant_to_load(TARGETS O3DE.GameLauncher VARIANTS Clients)
ly_set_gem_variant_to_load(TARGETS O3DE.ServerLauncher VARIANTS Servers)
ly_set_gem_variant_to_load(TARGETS O3DE.HeadlessServerLauncher VARIANTS HeadlessServers)
ly_set_gem_variant_to_load(TARGETS O3DE.UnifiedLauncher VARIANTS Unified)
