# Generated by O3DE install

set_property(TARGET Launcher.Unified.Static
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:release>:${LY_ROOT_FOLDER}/lib/Linux/release/Monolithic/libLauncher.Unified.Static.a>
)
set_property(TARGET Launcher.Unified.Static
    PROPERTY IMPORTED_LOCATION_RELEASE
        ${LY_ROOT_FOLDER}/lib/Linux/release/Monolithic/libLauncher.Unified.Static.a
)
