#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Generated by O3DE

ly_add_target(
    NAME Launcher.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Monolithic/Launcher.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Headless.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework.Headless
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES

    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Monolithic/Launcher.Headless.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Game.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        AZ::AzGameFramework
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Monolithic/Launcher.Game.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Server.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Monolithic/Launcher.Server.Static_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Launcher.Unified.Static IMPORTED STATIC
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE
            AZ::AzCore
            AZ::AzGameFramework
            Legacy::CryCommon
    RUNTIME_DEPENDENCIES
        AZ::AzCore
        AZ::AzGameFramework
        Legacy::CryCommon
    TARGET_PROPERTIES

)



set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Linux/Monolithic/Launcher.Unified.Static_${config}.cmake" OPTIONAL)
endforeach()

